version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: |
            npm install
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            npm run build
            npm run package
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - store_artifacts:
          path: ./target/
          

  prerelease:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: .
      - run: |
          npm run prerelease -- ./target/releaseVersion.txt ./target/artifactUrl.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./target/releaseVersion.txt
            - ./target/artifactUrl.txt
      - store_artifacts:
          path: ./target/

  stg-deploy:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "8c:a5:d5:3a:2c:f3:f3:be:fb:05:c8:e3:3d:bc:68:c0"
      - run: |
          ssh-keyscan s25627.gridserver.com >> ~/.ssh/known_hosts
          cat ./target/releaseVersion.txt
          cat ./target/artifactUrl.txt
          npm run deploy -- stg.windyroad.org `cat ./target/releaseVersion.txt` `cat ./target/artifactUrl.txt`

  prod-deploy:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "8c:a5:d5:3a:2c:f3:f3:be:fb:05:c8:e3:3d:bc:68:c0"
      - run: |
          ssh-keyscan s25627.gridserver.com >> ~/.ssh/known_hosts
          cat ./target/releaseVersion.txt
          cat ./target/artifactUrl.txt
          npm run deploy -- windyroad.com.au `cat ./target/releaseVersion.txt` `cat ./target/artifactUrl.txt`

workflows:
  version: 2

  ci:
    jobs:
      - build
      - prerelease:
          requires:
            - build
      - stg-deploy:
          requires:
            - prerelease

      - approve-prod-deploy:
          type: approval
          requires:
            - stg-deploy

      - prod-deploy:
          requires:
            - approve-prod-deploy