version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: |
            npm install
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            npm run build
            npm run package
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - store_artifacts:
          path: ./target/
          

  prerelease:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: .
      - run: |
          npm run prerelease

workflows:
  version: 2

  ci:
    jobs:
      - build
      - prerelease:
          requires:
            - build
