version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: |
            npm install
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            npm build
      - persist_to_workspace:
          root: ~/public
          paths:
            - ./*
  package:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: ~/public
      - run:
          command: |
            tar -czf ../windyroad.tar.gz *
      - store_artifacts:
          path: ~/windyroad.tar.gz
          destination: windyroad.tar.gz
      - persist_to_workspace:
          root: ~/
          paths:
            - windyroad.tar.gz

  release:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - attach_workspace:
          at: ~/public
      - run: |
          ls

workflows:
  version: 2

  ci:
    jobs:
      - build
      - package:
          requires:
            - build
      - release:
          requires:
            - package
