version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: |
            npm install
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: |
            npm run build
      - persist_to_workspace:
          root: public
          paths:
            - ./*
  package:
    docker:
      - image: circleci/node:9
    steps:
      - attach_workspace:
          at: public
      - run:
          command: |
            tar -czf ~/windyroad.tar.gz *
      - store_artifacts:
          path: ~/windyroad.tar.gz
          destination: windyroad.tar.gz
      - persist_to_workspace:
          root: ~/
          paths:
            - windyroad.tar.gz

  release:
    docker:
      - image: circleci/golang:latest
    tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: |
          go get -u github.com/tcnksm/ghr
          ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` output/

workflows:
  version: 2

  ci:
    jobs:
      - build
      - package:
          requires:
            - build
      - release:
          requires:
            - package
